### ISSUE TITLE
Can't connect to mcu? 

### ISSUE THREAD

**Issue by alekssobolewski** [KevinOConnor/klipper#1030]
Hi everyone!
I have a strange problem with my MKS Gen L board equipped with TMC2208s connected via UART.
I have also installed the latest 0.7 version.

Here is the most interesting (I think so) fragment of log file:
```
Receive: 96 2879.412219 2879.378655 13: seq: 19, analog_in_state oid=11 next_clock=52960000 value=7878
Receive: 97 2879.447253 2879.430241 18: seq: 1a, tmcuart_response oid=2 read='\n\xfaO \x80\x00\x02\x08%\x90'
Receive: 98 2879.495398 2879.483067 8: seq: 1b, tmcuart_response oid=2 read=''
Receive: 99 2879.512958 2879.483067 11: seq: 1b, shutdown clock=49888183 static_string_id=27
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 140, in _connect
    cb('connect')
  File "/home/pi/klipper/klippy/extras/tmc2208.py", line 197, in printer_state
    self.set_register(reg_name, val)
  File "/home/pi/klipper/klippy/extras/tmc2208.py", line 217, in set_register
    self.ifcnt = self.get_register("IFCNT")
  File "/home/pi/klipper/klippy/extras/tmc2208.py", line 203, in get_register
    [self.oid, msg, 10], 'tmcuart_response', self.oid)
  File "/home/pi/klipper/klippy/serialhdl.py", line 189, in send_with_response
    return src.get_response()
  File "/home/pi/klipper/klippy/serialhdl.py", line 223, in get_response
    raise error("Timeout on wait for '%s' response" % (self.name,))
error: Timeout on wait for 'tmcuart_response' response
```

In the OctoPrint terminal it connects to Klipper, but there is no proper connection to the mcu.

```
Send: FIRMWARE_RESTART
Recv: ok
Recv: // Klipper state: Disconnect
Send: FIRMWARE_RELOAD
Recv: // Printer is not ready
Recv: // The klippy host software is attempting to connect.  Please
Recv: // retry in a few moments.
Recv: !! Printer is not ready
WARNING! Received an error from the printer's firmware, ignoring that as configured but you might want to investigate what happened here! Error: Printer is not ready
Recv: ok
Send: M105
Recv: ok T:0
Send: M105
Recv: ok T:0
```

RESTART, FIRMWARE_RESTART and FIRMWARE_RELOAD does not help at all. I can see the uart LEDs on board blinking, but after that nothing happens. No LCD, no connection.

Everything have been working for days, the problem appeared today's morning ... :disappointed: 

[klippy.log](https://github.com/KevinOConnor/klipper/files/2705296/klippy.log)
[printer.cfg.txt](https://github.com/KevinOConnor/klipper/files/2705306/printer.cfg.txt)

**Comment by alekssobolewski** [comment]
UART wire from X motor driver become loose :laughing:
