### ISSUE TITLE
Parameter 'idle_timeout' update error

### ISSUE THREAD

**Issue by Achim01** [KevinOConnor/klipper#1712]
After reinstalling klipper this morning,
the klippy.log shows this:

Parameter 'idle_timeout' update error
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/extras/display/menu.py", line 1255, in update_parameters
    self.parameters[name] = get_status(eventtime)
  File "/home/pi/klipper/klippy/extras/idle_timeout.py", line 31, in get_status
    if state == "Printing":
NameError: global name 'state' is not defined

i have cut the log,
size bigger 50mb
[klippy.log](https://github.com/KevinOConnor/klipper/files/3266793/klippy.log)

**Comment by KevinOConnor** [comment]
Thanks.  Should be fixed now (commit 01f3b50e).

-Kevin
