### ISSUE TITLE
Print stops at layer 2

### ISSUE THREAD

**Issue by ZhenyaKa** [KevinOConnor/klipper#2450]
Try many times.
Hangs each time at layer 2 start.

There are some lines in log:
Got error -1 in write: (11)Resource temporarily unavailable
and at and:
Unhandled exception during run
Traceback (most recent call last):
  File "/home/octoprint/klipper/klippy/klippy.py", line 174, in run
    self.reactor.run()
  File "/home/octoprint/klipper/klippy/reactor.py", line 250, in run
    g_next.switch()
  File "/home/octoprint/klipper/klippy/reactor.py", line 277, in _dispatch_loop
    timeout = self._check_timers(eventtime)
  File "/home/octoprint/klipper/klippy/reactor.py", line 135, in _check_timers
    t.waketime = waketime = t.callback(eventtime)
  File "/home/octoprint/klipper/klippy/reactor.py", line 47, in invoke
    res = self.callback(eventtime)
  File "/home/octoprint/klipper/klippy/extras/web_dwc2.py", line 1575, in update_printdata
    self.print_data.get('last_zposes', [1])) == 1:
ZeroDivisionError: float division by zero

[2layer_stop_print.gcode.zip](https://github.com/KevinOConnor/klipper/files/4133669/2layer_stop_print.gcode.zip)
[klippy.log](https://github.com/KevinOConnor/klipper/files/4133673/klippy.log)

**Comment by KevinOConnor** [comment]
Unfortunately, the dwc2 code is not something we can support (it modifies the internal Klipper state).  You'll need to either reproduce the problem on the pristine code from this repo (and provide the corresponding log) or report the issue to the dwc2 developers.

-Kevin
