### ISSUE TITLE
Issue homing using G28

### ISSUE THREAD

**Issue by justh1n10** [KevinOConnor/klipper#2640]
When trying to home my printer using Octorpint I'm getting the following error, we've tried a few things in the config (discord support) suggested reporting this issue, here we go:

`Internal error on command:"G28"
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/gcode.py", line 234, in _process_commands
    handler(params)
  File "/home/pi/klipper/klippy/extras/homing_override.py", line 22, in cmd_G28
    self.prev_G28(params)
  File "/home/pi/klipper/klippy/gcode.py", line 498, in cmd_G28
    homing_state.home_axes(axes)
  File "/home/pi/klipper/klippy/homing.py", line 147, in home_axes
    self.toolhead.get_kinematics().home(self)
  File "/home/pi/klipper/klippy/kinematics/cartesian.py", line 93, in home
    self._home_axis(homing_state, axis, self.rails[axis])
  File "/home/pi/klipper/klippy/kinematics/cartesian.py", line 80, in _home_axis
    homing_state.home_rails([rail], forcepos, homepos)
  File "/home/pi/klipper/klippy/homing.py", line 116, in home_rails
    self.homing_move(movepos, endstops, hi.speed)
  File "/home/pi/klipper/klippy/homing.py", line 59, in homing_move
    rest_time = self._calc_endstop_rate(mcu_endstop, movepos, speed)
  File "/home/pi/klipper/klippy/homing.py", line 42, in _calc_endstop_rate
    return move_t / max_steps
ZeroDivisionError: float division by zero
`

[klippy.log](https://github.com/KevinOConnor/klipper/files/4366144/klippy.log)

Motherboard SKR 1.4

**Comment by justh1n10** [comment]
The issue is fixed, apparently  if homing_positive_dir: true then position_endstop can't be 0.
