### ISSUE TITLE
Print stop without notable error

### ISSUE THREAD

**Issue by basb227** [KevinOConnor/klipper#2661]
Hi,

I am running klipper on my custom FDM machine.
Mid print it stops without any notification of an error. 

The log mentions
```
stepcompress o=0 i=0 c=989 a=0: Invalid sequence
Exception in flush_handler
Traceback (most recent call last):
  File "/home/rock/klipper/klippy/toolhead.py", line 387, in _flush_handler
    self.flush_step_generation()
  File "/home/rock/klipper/klippy/toolhead.py", line 333, in flush_step_generation
    self.move_queue.flush()
  File "/home/rock/klipper/klippy/toolhead.py", line 171, in flush
    self.toolhead._process_moves(queue[:flush_count])
  File "/home/rock/klipper/klippy/toolhead.py", line 329, in _process_moves
    self._update_move_time(next_move_time)
  File "/home/rock/klipper/klippy/toolhead.py", line 288, in _update_move_time
    m.flush_moves(mcu_flush_time)
  File "/home/rock/klipper/klippy/mcu.py", line 729, in flush_moves
    self._name,))
error: Internal error in MCU 'mcu' stepcompress
```

Please let me know about similar experiences or a solution.

Kind regards,
Bas B

[klippy.log](https://github.com/KevinOConnor/klipper/files/4403173/klippy.log)

**Comment by KevinOConnor** [comment]
The root cause is a "Lost communication with MCU" error - see the FAQ: https://www.klipper3d.org/FAQ.html#i-keep-getting-random-lost-communication-with-mcu-errors

-Kevin
