### ISSUE TITLE
Internal error on command:"G1"

### ISSUE THREAD

**Issue by TheBigF1sh** [KevinOConnor/klipper#2817]
[New Text Document.txt](https://github.com/KevinOConnor/klipper/files/4567961/New.Text.Document.txt)

Hi 

I think I can see a few issues around this but states code upgraded to resolve - however this is the second time I have now had a cancelled print due to the G1 error.

Any help you can provide to enable me to circumvent would be greatly appreciated -i have attached a log and the offending point at which the print cancelled below :

stepcompress o=1 i=0 c=259 a=0: Invalid sequence
Internal error on command:"G1"
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/gcode.py", line 234, in _process_commands
    handler(params)
  File "/home/pi/klipper/klippy/gcode.py", line 482, in cmd_G1
    self.move_with_transform(self.last_position, self.speed)
  File "/home/pi/klipper/klippy/extras/bed_mesh.py", line 176, in move
    self.toolhead.move(split_move, speed)
  File "/home/pi/klipper/klippy/toolhead.py", line 412, in move
    self.move_queue.add_move(move)
  File "/home/pi/klipper/klippy/toolhead.py", line 182, in add_move
    self.flush(lazy=True)
  File "/home/pi/klipper/klippy/toolhead.py", line 171, in flush
    self.toolhead._process_moves(queue[:flush_count])
  File "/home/pi/klipper/klippy/toolhead.py", line 330, in _process_moves
    self._update_move_time(next_move_time)
  File "/home/pi/klipper/klippy/toolhead.py", line 289, in _update_move_time
    m.flush_moves(mcu_flush_time)
  File "/home/pi/klipper/klippy/mcu.py", line 727, in flush_moves
    self._name,))
error: Internal error in MCU 'mcu' stepcompress
Internal error on command:"G1"

**Comment by KevinOConnor** [comment]
The root cause of your issue is a "Heater extruder not heating at expected rate" issue.  Your extruder temperature is fluctuating wildly - that's usually an indicator of a faulty thermistor or its wiring.

-Kevin

**Comment by TheBigF1sh** [comment]
Thanks for the speedy response. Ill take a look at the wiring.
