### ISSUE TITLE
Flash is success but getting 'Error: Serial connection closed'

### ISSUE THREAD

**Issue by MichaelNewham** [KevinOConnor/klipper#3047]
- MELZI Board 2.0
- Octoprint Version 1.4.0
- Firmware Version & Name (see pic from Octoprint Terminal below)

Can't get past this part of configuration. RESTART and FIRMWARE_RESTART gets me nowhere..

What next to try?

Thanks in advance, Michael.

Attachments:
1. [klippy.log](https://github.com/KevinOConnor/klipper/files/4871021/klippy.log)

2. ![Firmware Version from Octoprint Terminal](https://user-images.githubusercontent.com/11710523/86491934-3a41ee00-bd64-11ea-8620-fd346d32b70c.png)

3. [Makeflash and Avrdude Flash Success.txt](https://github.com/KevinOConnor/klipper/files/4871023/Makeflash.and.Avrdude.Flash.Success.txt)

**Comment by MichaelNewham** [comment]
Guys, any ideas on the above.

a) Flashing works -
  Flashing out/klipper.elf.hex to /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0 via avrdude

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e9705 (probably m1284p)
avrdude: reading input file "out/klipper.elf.hex"
avrdude: writing flash (21928 bytes):

Writing | ################################################## | 100% 2.77s

avrdude: 21928 bytes of flash written
avrdude: verifying flash memory against out/klipper.elf.hex:
avrdude: load data flash data from input file out/klipper.elf.hex:
avrdude: input file out/klipper.elf.hex contains 21928 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 2.41s

avrdude: verifying ...
avrdude: 21928 bytes of flash verified

avrdude: safemode: Fuses OK (E:00, H:00, L:00)

avrdude done.  Thank you.

b) Configured 'Printer.cfg' with the following MCU parameter is in the home directory - 
[mcu]
serial: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0 

c) Following is output from the Octoprint Terminal -

Connecting to: /tmp/printer
Changing monitoring state from "Offline" to "Opening serial port"
Connected to: Serial<id=0xad861350, open=True>(port='/tmp/printer', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=10.0, xonxoff=False, rtscts=False, dsrdtr=False), starting monitor
Changing monitoring state from "Opening serial port" to "Connecting"
Send: N0 M110 N0*125
Recv: ok
Send: N0 M110 N0*125
Changing monitoring state from "Connecting" to "Operational"
Recv: ok
Send: N0 M110 N0*125
Recv: ok
Send: N1 M115*39
Recv: ok FIRMWARE_VERSION:v0.8.0-627-g5dc0c8aa FIRMWARE_NAME:Klipper
Send: N2 M21*18
Recv: ok

c) Klippy Log keep repeating the following. (FIRMWARE-RESET does nothing)
Build file /home/pi/klipper/klippy/../out/klipper.dict(5770): Fri Jun 26 01:08:09 2020
Last MCU build version: v0.8.0-617-g54166567-20200626_010809-Tronxy-4
Last MCU build tools: gcc: (GCC) 5.4.0 binutils: (GNU Binutils) 2.26.20160125
Last MCU build config: RECEIVE_WINDOW=192 BUS_PINS_spi=PB6,PB5,PB7 SERIAL_BAUD=115200 STEP_DELAY=-1 ADC_MAX=1023 PWM_MAX=255 CLOCK_FREQ=16000000 BUS_PINS_twi=PC0,PC1 MCU=atmega1284p STATS_SUMSQ_BASE=256 RESERVE_PINS_serial=PD0,PD1
Build file /home/pi/klipper/klippy/../out/klipper.elf(41952): Fri Jun 26 01:08:17 2020
Wait for identify_response
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/serialhdl.py", line 68, in _get_identify_data
    params = self.send_with_response(msg, 'identify_response')
  File "/home/pi/klipper/klippy/serialhdl.py", line 186, in send_with_response
    return src.get_response(cmd, self.default_cmd_queue)
  File "/home/pi/klipper/klippy/serialhdl.py", line 242, in get_response
    self.serial.raw_send_wait_ack(cmd, minclock, minclock, cmd_queue)
  File "/home/pi/klipper/klippy/serialhdl.py", line 178, in raw_send_wait_ack
    raise error("Serial connection closed")
error: Serial connection closed
Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer
Klipper state: Not ready

All help appreciated

**Comment by MichaelNewham** [comment]
SUCCESS:

I got a coffee and  re-read the FAQ, in particular - 

[6. How do I change the serial baud rate?](https://www.klipper3d.org/FAQ.html#how-do-i-change-the-serial-baud-rate)

I changed the baud rate under {MCU) to match the baud rate in Octoprint/Serial Connection/Baudrate.

[mcu]
serial: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0 ; I ran this command at the Tronxy SSH command propt to get this info - ls /dev/serial/by-id/*
baud: 115200

(I also presume this baud rate matched the one I chose(?) when building the firmware.)
