### ISSUE TITLE
Neopixel error with last comit 8215617

### ISSUE THREAD

**Issue by elpopo-eng** [KevinOConnor/klipper#3509]
Hello with this [commit ](https://github.com/KevinOConnor/klipper/commit/821561708d0973ba2dbc93fabff381075c0b2aed)we have this error in the initialization (line 1038) :
```
MCU error during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 151, in _connect
    cb()
  File "/home/pi/klipper/klippy/extras/neopixel.py", line 107, in send_data
    reqclock=BACKGROUND_PRIORITY_CLOCK)
  File "/home/pi/klipper/klippy/mcu.py", line 378, in send
    raise error(str(e))
error: Unable to obtain 'neopixel_result' response
Build file /home/pi/klipper/klippy/../.config(1067): Mon Oct  5 11:37:14 2020
```
Here under the kliiper log
[klippy.zip](https://github.com/KevinOConnor/klipper/files/5494594/klippy.zip)

Regards

**Comment by elpopo-eng** [comment]
Clone
