### ISSUE TITLE
PWM_MAX FW constant missing for LPC1769

### ISSUE THREAD

**Issue by zellneralex** [KevinOConnor/klipper#3932]
I tried to setup the following:
[fan]
pin = P2.1
kick_start_time = 0.5
off_below = 0.10
cycle_time = 0.00005
hardware_pwm = true

Pin 2.1 is a HW PWM Pin. I get a fail that says fw constant missing.
[klippy.log](https://github.com/KevinOConnor/klipper/files/5978178/klippy.log)

`Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 151, in _connect
    cb()
  File "/home/pi/klipper/klippy/mcu.py", line 581, in _connect
    self._send_config(None)
  File "/home/pi/klipper/klippy/mcu.py", line 520, in _send_config
    cb()
  File "/home/pi/klipper/klippy/mcu.py", line 203, in _build_config
    self._pwm_max = self._mcu.get_constant_float("PWM_MAX")
  File "/home/pi/klipper/klippy/mcu.py", line 702, in get_constant_float
    return self._serial.get_msgparser().get_constant_float(name)
  File "/home/pi/klipper/klippy/msgproto.py", line 404, in get_constant_float
    return self.get_constant(name, default, parser=float)
  File "/home/pi/klipper/klippy/msgproto.py", line 396, in get_constant
    raise error("Firmware constant '%s' not found" % (name,))
error: Firmware constant 'PWM_MAX' not found
Build file /home/pi/klipper/klippy/../.config(1029): Sun Feb 14 18:37:56 2021`

**Comment by FHeilmann** [comment]
LPC176x doesn't support hardware pwm, remove 
`hardware_pwm = true`
from your config and everything should start working.

**Comment by zellneralex** [comment]
It does, will need to connect a scope to see if that is running the needed requested 20 KHz PWM signal for the fan with SW PWM.

**Comment by zellneralex** [comment]
If possible a better Error message would be helpful.
