### ISSUE TITLE
Failed to home z: Timeout during homing

### ISSUE THREAD

**Issue by perikanttila** [KevinOConnor/klipper#4170]
I have a printer that has up/down moving bed. when the bed is down it takes quite long time to raise it in order to reach probe that is located in the X-carriage. 

I use homing override as I have servo probe that needs to be stowed after probing. Z motor uses virtual end stop.

My issue is that how I can get rid of the timeout. The homing works if the bed is very near to the probe when homing.

**Comment by perikanttila** [comment]
[klippy.log](https://github.com/KevinOConnor/klipper/files/6318599/klippy.log)

**Comment by perikanttila** [comment]
Failed to home z: Timeout during homing
Failed to home z: Timeout during homing
Script running error
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/extras/display/menu.py", line 956, in dispatch_gcode
    self.gcode.run_script(script)
  File "/home/pi/klipper/klippy/gcode.py", line 200, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/pi/klipper/klippy/gcode.py", line 182, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/extras/homing_override.py", line 60, in cmd_G28
    self.template.run_gcode_from_command(context)
  File "/home/pi/klipper/klippy/extras/gcode_macro.py", line 68, in run_gcode_from_command
    self.gcode.run_script_from_command(self.render(context))
  File "/home/pi/klipper/klippy/gcode.py", line 197, in run_script_from_command
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/pi/klipper/klippy/gcode.py", line 182, in _process_commands
    handler(gcmd)
  File "/home/pi/klipper/klippy/extras/homing_override.py", line 23, in cmd_G28
    self.prev_G28(gcmd)
  File "/home/pi/klipper/klippy/extras/homing.py", line 199, in cmd_G28
    kin.home(homing_state)
  File "/home/pi/klipper/klippy/kinematics/corexy.py", line 73, in home
    homing_state.home_rails([rail], forcepos, homepos)
  File "/home/pi/klipper/klippy/extras/homing.py", line 150, in home_rails
    hmove.homing_move(movepos, hi.second_homing_speed)
  File "/home/pi/klipper/klippy/extras/homing.py", line 94, in homing_move
    raise self.printer.command_error(error)
CommandError: Failed to home z: Timeout during homing

**Comment by perikanttila** [comment]
was my bad - probe was not fast enough to go down.
