### ISSUE TITLE
Failed to read file FIRMWARE.CUR

### ISSUE THREAD

**Issue by Sonnenwerk** [KevinOConnor/klipper#4430]
**commands**
cd klipper
sudo service klipper stop
./scripts/flash-sdcard.sh /dev/serial/by-id/usb-Klipper_stm32f103xe_35FFDD05524E343534830443-if00 btt-skr-mini-e3-v1.2

**leads to:**

Flashing /home/pi/klipper/out/klipper.bin to /dev/serial/by-id/usb-Klipper_stm32f103xe_35FFDD05524E343534830443-if00
Checking FatFS CFFI Build...
Connecting to MCU...Connected
Checking Current MCU Configuration...Done
MCU needs restart: is_config=0, is_shutdown=1
Attempting MCU Reset...Done
Waiting for device to reconnect...Done
Connecting to MCU...Connected
Initializing SD Card and Mounting file system...

SD Card Information:
Version: 2.0
SDHC/SDXC: True
Write Protected: False
Sectors: 15564800
manufacturer_id: 39
oem_id: PH
product_name: SD08G
product_revision: 3.48
serial_number: 7CD448AC
manufacturing_date: 7/2014
capacity: 7.4 GiB
fs_type: FAT32
volume_label:
volume_serial: 469795931
Uploading Klipper Firmware to SD Card...Done
Validating Upload...Done
Firmware Upload Complete: firmware.bin, Size: 22988, Checksum (SHA1): F87FC224CA05640C89A6598423E5F0E9E9CA1793
Attempting MCU Reset...Done
Waiting for device to reconnect....Done
Connecting to MCU...Connected
Verifying Flash...
SD Card Flash Error: Failed to read file FIRMWARE.CUR
Traceback (most recent call last):
  File "/home/pi/klipper/scripts/spi_flash/spi_flash.py", line 1105, in main
    spiflash.run()
  File "/home/pi/klipper/scripts/spi_flash/spi_flash.py", line 1063, in run
    self.run_reactor_task(self.run_verify)
  File "/home/pi/klipper/scripts/spi_flash/spi_flash.py", line 1045, in run_reactor_task
    k_reactor.run()
  File "/home/pi/klipper/klippy/reactor.py", line 269, in run
    g_next.switch()
  File "/home/pi/klipper/klippy/reactor.py", line 310, in _dispatch_loop
    timeout = self._check_timers(eventtime, busy)
  File "/home/pi/klipper/klippy/reactor.py", line 156, in _check_timers
    t.waketime = waketime = t.callback(eventtime)
  File "/home/pi/klipper/klippy/reactor.py", line 48, in invoke
    res = self.callback(eventtime)
  File "/home/pi/klipper/scripts/spi_flash/spi_flash.py", line 1034, in run_verify
    self.mcu_conn.verify_flash(self.firmware_checksum)
  File "/home/pi/klipper/scripts/spi_flash/spi_flash.py", line 967, in verify_flash
    raise SPIFlashError(msg)
SPIFlashError: Failed to read file FIRMWARE.CUR

As klipper does not connect proberbly to the firmware, i can not see, if flashing updated correctly.
I use the klipper version as of git today.
For analysis i would suggest to add version also to the output of the flashing process (and maybe we dont need all SD Card info)

**Comment by Carbonneau** [comment]
+1 on this issue, i have the same issue with my btt-skr-mini-e3-v2.
