### ISSUE TITLE
'mcu': Unable to connect on Duet3D 2 WiFi via fluidd

### ISSUE THREAD

**Issue by WickyX** [KevinOConnor/klipper#4459]
I recently began a rebuild of my Airwolf3D AXIOM in which I replaced my RAMBo with a Duet3D 2 WiFi and Raspberry Pi running Klipper via fluidd.  I have followed the guides (linked as follows) at [klipper3d.org](https://www.klipper3d.org/Installation.html#configuring-klipper) and [docs.fluid.xyz](https://docs.fluidd.xyz/installation/fluiddpi) and everything seemed to be going well until I started getting the following message during the Klipper startup in fluidd: 

mcu 'mcu': Unable to connect
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Error configuring printer

I tried reflashing Klipper to my Duet however the issue persists.  My klippy.log ends with the following:

Traceback (most recent call last):
  File "/home/pi/klipper/klippy/serialhdl.py", line 69, in _get_identify_data
    params = self.send_with_response(msg, 'identify_response')
  File "/home/pi/klipper/klippy/serialhdl.py", line 258, in send_with_response
    return src.get_response([cmd], self.default_cmd_queue)
  File "/home/pi/klipper/klippy/serialhdl.py", line 316, in get_response
    cmd_queue)
  File "/home/pi/klipper/klippy/serialhdl.py", line 250, in raw_send_wait_ack
    self._error("Serial connection closed")
  File "/home/pi/klipper/klippy/serialhdl.py", line 62, in _error
    raise error(self.warn_prefix + (msg % params))
error: mcu 'mcu': Serial connection closed

Any assistance that can be provided on this matter would be immensely appreciated.  I have also attached my klippy.log  and printer.cfg files in hopes that you may be able to catch something I have overlooked, etc.  Please note that I am not actually trying to use printer.cfg with a .txt extension, I simply added it so that I would be able to attach it here.

[klippy (2).log](https://github.com/KevinOConnor/klipper/files/6759665/klippy.2.log)
[printer.cfg.txt](https://github.com/KevinOConnor/klipper/files/6759668/printer.cfg.txt)

**Comment by WickyX** [comment]
I forgot to mention that I also added a BLTouch to my printer, as well.
