### ISSUE TITLE
Config error: Option 'microsteps' in section 'stepper_extruder' must be specified

### ISSUE THREAD

**Issue by Moutarderie** [KevinOConnor/klipper#4680]
I'm getting the error `Option 'microsteps' in section 'stepper_extruder' must be specified`, with the btt skr v1.4 turbo config.

I thought that the tmc2209 stepper_x would inherit the microsteps from the stepper_x

```
Starting Klippy...
Args: ['/home/pi/klipper/klipper/klippy/klippy.py', '/home/pi/printer.cfg', '-l', '/tmp/klippy.log']
Git version: 'v0.9.1-773-gc84956be'
CPU: 4 core ARMv7 Processor rev 4 (v7l)
Python: '2.7.16 (default, Oct 10 2019, 22:02:15) \n[GCC 8.3.0]'
Start printer at Fri Sep 10 22:03:19 2021 (1631307799.7 1970.8)
===== Config file =====
[stepper_x]
step_pin = P2.2
dir_pin = P2.6
enable_pin = !P2.1
microsteps = 16
rotation_distance = 40
endstop_pin = !P1.29
position_endstop = 0
position_max = 300
homing_speed = 50

[tmc2209 stepper_x]
uart_pin = P1.10
run_current = 0.950
hold_current = 0.500
stealthchop_threshold = 999999

[stepper_y]
step_pin = P0.19
dir_pin = P0.20
enable_pin = !P2.8
microsteps = 16
rotation_distance = 40
endstop_pin = !P1.28
position_endstop = 0
position_max = 255
homing_speed = 50

[tmc2209 stepper_y]
uart_pin = P1.9
run_current = 0.950
hold_current = 0.500
stealthchop_threshold = 999999

[stepper_z]
step_pin = P0.22
dir_pin = !P2.11
enable_pin = !P0.21
microsteps = 16
rotation_distance = 8
endstop_pin = probe:z_virtual_endstop
position_endstop = 0
position_max = 300

[tmc2209 stepper_z]
uart_pin = P1.8
run_current = 0.950
hold_current = 0.500
stealthchop_threshold = 999999

[stepper_z1]
step_pin = P1.15
dir_pin = !P1.14
enable_pin = !P1.16
microsteps = 16
rotation_distance = 8
endstop_pin = probe:z_virtual_endstop
position_endstop = 0
position_max = 300

[tmc2209 stepper_z1]
uart_pin = P1.1
run_current = 0.950
hold_current = 0.500
stealthchop_threshold = 999999

[extruder]
step_pin = P2.13
dir_pin = !P0.11
enable_pin = !P2.12
microsteps = 16
nozzle_diameter = 0.400
filament_diameter = 1.750
heater_pin = P2.7
sensor_type = EPCOS 100K B57560G104F
sensor_pin = P0.24
control = pid
pid_kp = 22.2
pid_ki = 1.08
pid_kd = 114
min_temp = 0
max_temp = 265

[tmc2209 stepper_extruder]
uart_pin = P1.4
run_current = 0.950
hold_current = 0.500
stealthchop_threshold = 999999

[heater_bed]
heater_pin = P2.5
sensor_type = EPCOS 100K B57560G104F
sensor_pin = P0.25
control = pid
pid_kp = 54.027
pid_ki = 0.770
pid_kd = 948.182
min_temp = 0
max_temp = 110

[fan]
pin = P2.3

[mcu]
serial = /dev/serial/by-id/usb-Klipper_lpc1769_1FB0FF0E871C4AAF883D7C5DC52000F5-if00

[printer]
kinematics = cartesian
max_velocity = 400
max_accel = 3000
max_z_velocity = 10
max_z_accel = 100

[sdcard_loop]

[bltouch]
sensor_pin = ^P0.10
control_pin = P2.0
x_offset = 36.5
y_offset = 4.0
z_offset = 5.0
speed = 5.0
samples = 2
sample_retract_dist = 5
samples_result = average
samples_tolerance = 0.100
samples_tolerance_retries = 2

[safe_z_home]
home_xy_position = 150,127.5
speed = 50
z_hop = 10
z_hop_speed = 5

[display]
lcd_type = st7920
cs_pin = EXP1_4
sclk_pin = EXP1_5
sid_pin = EXP1_3
encoder_pins = ^EXP2_3, ^EXP2_5
click_pin = ^!EXP1_2

[output_pin beeper]
pin = EXP1_1

[board_pins]
aliases = 
	EXP1_1=P1.30, EXP1_3=P1.18, EXP1_5=P1.20, EXP1_7=P1.22, EXP1_9=<GND>,
	EXP1_2=P0.28, EXP1_4=P1.19, EXP1_6=P1.21, EXP1_8=P1.23, EXP1_10=<5V>,
	EXP2_1=P0.17, EXP2_3=P3.26, EXP2_5=P3.25, EXP2_7=P1.31, EXP2_9=<GND>,
	EXP2_2=P0.15, EXP2_4=P0.16, EXP2_6=P0.18, EXP2_8=<RST>, EXP2_10=<NC>

[filament_switch_sensor filament_sensor]
runout_gcode = 
	M600 ;pause Makro
switch_pin = P1.26

[pause_resume]

[gcode_macro M600]
gcode = 
	{% set X = params.X|default(50)|float %}
	{% set Y = params.Y|default(0)|float %}
	{% set Z = params.Z|default(10)|float %}
	SAVE_GCODE_STATE NAME=M600_state
	PAUSE
	G91
	G1 E-.8 F2700
	G1 Z{Z}
	G90
	G1 X{X} Y{Y} F3000
	G91
	G1 E-50 F1000
	RESTORE_GCODE_STATE NAME=M600_state

[gcode_arcs]
resolution = 1.0
=======================
Config error
Traceback (most recent call last):
  File "/home/pi/klipper/klipper/klippy/klippy.py", line 157, in _connect
    self._read_config()
  File "/home/pi/klipper/klipper/klippy/klippy.py", line 141, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/pi/klipper/klipper/klippy/klippy.py", line 130, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/pi/klipper/klipper/klippy/extras/tmc2209.py", line 96, in load_config_prefix
    return TMC2209(config)
  File "/home/pi/klipper/klipper/klippy/extras/tmc2209.py", line 69, in __init__
    cmdhelper = tmc.TMCCommandHelper(config, self.mcu_tmc, current_helper)
  File "/home/pi/klipper/klipper/klippy/extras/tmc.py", line 230, in __init__
    TMCMicrostepHelper(config, mcu_tmc)
  File "/home/pi/klipper/klipper/klippy/extras/tmc.py", line 501, in TMCMicrostepHelper
    mres = ms_config.getchoice('microsteps', steps)
  File "/home/pi/klipper/klipper/klippy/configfile.py", line 73, in getchoice
    c = self.getint(option, default, note_valid=note_valid)
  File "/home/pi/klipper/klipper/klippy/configfile.py", line 62, in getint
    minval, maxval, note_valid=note_valid)
  File "/home/pi/klipper/klipper/klippy/configfile.py", line 33, in _get_wrapper
    % (option, self.section))
Error: Option 'microsteps' in section 'stepper_extruder' must be specified
Option 'microsteps' in section 'stepper_extruder' must be specified

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted
Klipper state: Not ready
```

**Comment by LeandroMarceddu** [comment]
This has changed, move the microsteps from the [stepper_x] to the [tmc2209 stepper_x] section.
